---
- hosts: all
  vars:
    venv_dir: /opt/test-env
    output:  /root/vevn.zip
  remote_user: root
  tasks:
    - name: Check if pip is installed
      apt:
        name:
          - python3-pip
        state: present

    - name: Install virtualenv
      pip:
        executable: pip3
        name: virtualenv

    - name: Copy requirements to the host
      copy:
        src: requirements.txt
        dest: /root/requirements.txt

    - name: Create virtualenv
      command: python3 -m virtualenv  --clear "{{ venv_dir }}"

    - name: Install packages from the requirements.txt
      pip:
        requirements: /root/requirements.txt
        virtualenv: "{{ venv_dir }}"

    - name: Create a zip archive with virtualenv
      archive:
        format: zip
        dest: "{{ output }}"
